name: ci

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

jobs:
 
  create-sql-seed:
    runs-on: ubuntu-latest
    container: 
      image: pipelineimages.azurecr.io/utilities/dotnet-ingestion-pipeline:latest
      credentials:
        username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

    env:
      ASPNETCORE_ENVIRONMENT: ci
      PGPASSWORD: password
    
    services:
      postgres:
        image: postgres:12.9
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: database_brightbase_healthcare
          POSTGRES_USER: postgres
          POSTGRES_PORT: 5432
        ports:
        - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:  
    - name: Set - Tag
      id: set-tag
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
   
    - name : Make resource directory.
      run : "mkdir ./resources"

    - name: Download from Azure Blob Storage
      run: az storage blob download --container-name nza --file "./resources/nza2.zip" --name nza.zip --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}"
    
    - name: Decompress
      uses: TonyBogdanov/zip@1.0
      with:
        args: unzip -qq ./resources/nza.zip -d ./resources

    - name: Check out the repo
      uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675
      with:
        path: './repository'

    - run: dotnet publish ./repository/Source/Consoles/Silvester.BrightBase.Healthcare.Seeding.Cli/Silvester.BrightBase.Healthcare.Seeding.Cli.csproj -c Release -o ./build/publish

    - run: dotnet ./build/publish/Silvester.BrightBase.Healthcare.Seeding.Cli.dll seed --product-summaries ./resources/01_DBC.csv --activity-summaries ./resources/02_DBC_PROFIEL.csv --activities ./resources/03_REF_ZAT.csv --diagnoses ./resources/04_REF_DGN.csv --products ./resources/05_REF_ZPD.csv --specialties ./resources/06_REF_SPC.csv
    - run: pg_dump --host postgres --port 5432 -U postgres -d database_brightbase_healthcare -Fp > seed.sql
    - name: Archive Seed Artifact
      uses: actions/upload-artifact@v2
      with:
        name: sql-seed
        path: seed.sql
        retention-days: 1
  
    - name: DOCKER - Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
        registry: pipelineimages.azurecr.io
    
    - name: DOCKER - Setup QEMU
      uses: docker/setup-qemu-action@v1

    - name: DOCKER - Setup BuildX 
      uses: docker/setup-buildx-action@v1
      
    - name: DOCKER - Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true 
        file: ./repository/Dockerfile
        tags: |
          pipelineimages.azurecr.io/sources/nza:${{ steps.set-tag.outputs.tag }}
          pipelineimages.azurecr.io/sources/nza:latest